name: Dependabot auto-merge

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: lernejo/reusable-workflows/.github/workflows/automerge-dependabot.yml@main
    secrets: inherit
